name = "GoogleAnalytics"
uuid = "7ea187bb-140a-41e8-a18c-12614bc9f53b"
authors = ["Val Lyashov", "Envato"]
version = "0.1.0"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
